/** Maps internal icon keys (ServiceIcon / catalog) to Flaticon UIcons slugs (fi-rr-*). */
export const SERVICE_ICON_MAP = {
  scooter: "scooter",
  "car-front": "car-alt",
  taxi: "taxi",
  wrench: "wrench-simple",
  tools: "tools",
  warning: "triangle-warning",
  "tow-truck": "truck-tow",
  "hard-hat": "hard-hat",
  "calendar-star": "calendar-star",
  briefcase: "briefcase",
  cart: "cart-shopping-fast",
  "grid-four": "grid",
  shield: "shield-check",
  diamond: "benefit-diamond",
  headset: "headset",
  lock: "lock",
  "doc-shield": "shield-check",
  broom: "broom",
  pest: "bug",
  faucet: "faucet",
  bolt: "bolt-auto",
  hammer: "hammer",
  "paint-roller": "paint-roller",
  shovel: "shovel",
  "brick-wall": "block-brick",
  "welding-mask": "mask-face",
  ibeam: "ruler-triangle",
  "ac-unit": "air-conditioner",
  toolbox: "tool-box",
  venue: "landmark-alt",
  cloche: "plate-utensils",
  "arch-flowers": "flower-bouquet",
  camera: "camera-retro",
  "headphones-music": "headphones",
  "clipboard-check": "clipboard-check",
  truck: "truck-bolt",
  tutor: "user-graduate",
  beauty: "lipstick",
  yoga: "candle-lotus-yoga",
  paw: "paw-claws",
  walker: "walker",
  "job-search": "search-alt",
  megaphone: "megaphone",
  freelancer: "laptop-code",
  buildings: "building",
  "tag-percent": "badge-percent",
  house: "house-blank",
  "car-side": "car-side",
  "grad-cap": "graduation-cap",
  calendar: "calendar",
  worker: "person-carry-box",
  person: "user",
  "grid-menu": "apps",
} as const;

export type ServiceIconName = keyof typeof SERVICE_ICON_MAP;

export const CATEGORY_FLATICON: Record<string, string> = {
  "home-services": "house-blank",
  "construction-services": "hard-hat",
  "beauty-wellness": "lipstick",
  "events-media": "camera-retro",
  "equipment-rentals": "box-alt",
  "vehicle-services": "car-side",
  "accommodation-services": "building",
  "jobs-gigs": "briefcase",
  "manpower-support": "users-alt",
  "custom-services": "sparkles",
};

export const VEHICLE_TYPE_ICONS: Record<string, string> = {
  bike: "motorcycle",
  auto: "taxi",
  taxi: "taxi",
  premium: "car-side",
  tata_ace: "truck-bolt",
  pickup: "truck-bolt",
  mini_truck: "truck-bolt",
  truck: "truck-bolt",
  house_shifting: "box-alt",
};

/** Legacy emoji strings → Flaticon slugs for detail pages and seeded DB values. */
export const EMOJI_FLATICON: Record<string, string> = {
  "🏠": "house-blank",
  "👷": "hard-hat",
  "💅": "lipstick",
  "📸": "camera-retro",
  "📦": "box-alt",
  "🚗": "car-side",
  "🏨": "building",
  "💼": "briefcase",
  "👥": "users-alt",
  "✨": "sparkles",
  "🎓": "graduation-cap",
  "⭐": "circle-star",
  "🛡️": "shield-check",
  "🧰": "tool-box",
  "🦺": "hard-hat",
  "📟": "mobile-notch",
  "🧴": "hand-sparkles",
  "🔩": "wrench-simple",
  "🪜": "stairs",
  "🚪": "door-open",
  "🔌": "plug",
  "🚰": "faucet",
  "🏗️": "building",
  "🔨": "hammer",
  "📏": "ruler-triangle",
  "⛑️": "hard-hat",
  "🪣": "bucket",
  "⚙️": "settings-sliders",
  "🚧": "road-barrier",
  "📱": "mobile-notch",
  "💄": "lipstick",
  "🧻": "toilet-paper-blank",
  "♨️": "heat",
  "🪞": "circle",
  "🖌️": "paintbrush-pencil",
  "💡": "lightbulb-on",
  "🪑": "chair",
  "🎉": "party-horn",
  "📷": "camera-retro",
  "🔊": "volume",
  "🎀": "gift",
  "💻": "laptop-code",
  "🎒": "backpack",
  "🏛️": "landmark-alt",
  "🔋": "battery-bolt",
  "🚚": "truck-bolt",
  "🔧": "wrench-simple",
  "📋": "clipboard-list",
  "🛒": "cart-shopping-fast",
  "🪪": "id-card-clip-alt",
  "💳": "credit-card",
  "🛣️": "road",
  "🧽": "hand-sparkles",
  "🛞": "circle",
  "🔑": "key",
  "🅿️": "parking",
  "🛏️": "bed",
  "📶": "wifi",
  "🧺": "basket-shopping-plus",
  "❄️": "air-conditioner",
  "🚿": "shower",
  "🔐": "lock",
  "📄": "add-document",
  "📝": "pen-clip",
  "🔔": "bell",
  "💬": "comment-alt",
  "📹": "video-camera",
  "✅": "check-circle",
  "👤": "user",
  "🏢": "building",
  "👔": "vest-patches",
  "🧹": "broom",
  "📻": "radio",
  "📞": "phone-call",
  "🚐": "bus",
  "🌀": "spinner",
  "✕": "cross",
};

export function resolveFlaticonName(input: string, categorySlug?: string): string {
  if (input in SERVICE_ICON_MAP) {
    return SERVICE_ICON_MAP[input as ServiceIconName];
  }
  if (categorySlug && CATEGORY_FLATICON[categorySlug]) {
    return CATEGORY_FLATICON[categorySlug];
  }
  if (EMOJI_FLATICON[input]) {
    return EMOJI_FLATICON[input];
  }
  if (VEHICLE_TYPE_ICONS[input]) {
    return VEHICLE_TYPE_ICONS[input];
  }
  if (/^[a-z0-9-]+$/.test(input)) {
    return input;
  }
  return "apps";
}
