import type { AccommodationTypeSlug } from "./constants";

const IMG = (label: string) =>
  `https://placehold.co/800x500/5b1a8a/ffffff?text=${encodeURIComponent(label)}`;

type PropertySeed = {
  propertyType: AccommodationTypeSlug;
  serviceSlug: string;
  title: string;
  location: string;
  area: string;
  lat: number;
  lng: number;
  pricePaise: number;
  priceUnit: "month" | "night";
  depositPaise: number;
  rating: number;
  roomType: string;
  hasAc: boolean;
  isFurnished: boolean;
  sharingType: "single" | "double";
  foodIncluded: boolean;
  genderPreference: "any" | "male" | "female";
  amenities: string[];
  rules: string[];
  ownerName: string;
  ownerPhone: string;
};

const OWNERS = [
  { name: "Srinivas Reddy", phone: "9876511001", rating: 4.8 },
  { name: "Anjali Properties", phone: "9876511002", rating: 4.7 },
  { name: "Hyderabad Stays", phone: "9876511003", rating: 4.9 },
  { name: "Metro Homes", phone: "9876511004", rating: 4.6 },
  { name: "Green Valley PG", phone: "9876511005", rating: 4.5 },
];

export const PROPERTY_SEED_TEMPLATES: PropertySeed[] = [
  {
    propertyType: "rooms",
    serviceSlug: "rooms",
    title: "Spacious Single Room — Gachibowli",
    location: "Near Wipro Circle, Gachibowli",
    area: "Gachibowli",
    lat: 17.4401,
    lng: 78.3489,
    pricePaise: 899900,
    priceUnit: "month",
    depositPaise: 1500000,
    rating: 4.7,
    roomType: "Single room with attached bath",
    hasAc: true,
    isFurnished: true,
    sharingType: "single",
    foodIncluded: false,
    genderPreference: "any",
    amenities: ["Wi-Fi", "Power backup", "Housekeeping", "Parking"],
    rules: ["No smoking indoors", "Visitors till 8 PM", "ID proof mandatory"],
    ownerName: OWNERS[0].name,
    ownerPhone: OWNERS[0].phone,
  },
  {
    propertyType: "rooms",
    serviceSlug: "rooms",
    title: "Budget Room — Kondapur",
    location: "Kondapur Main Road",
    area: "Kondapur",
    lat: 17.4612,
    lng: 78.3568,
    pricePaise: 649900,
    priceUnit: "month",
    depositPaise: 1000000,
    rating: 4.4,
    roomType: "Single room, shared bath",
    hasAc: false,
    isFurnished: false,
    sharingType: "single",
    foodIncluded: false,
    genderPreference: "any",
    amenities: ["Wi-Fi", "Water purifier"],
    rules: ["Monthly rent in advance", "No pets"],
    ownerName: OWNERS[1].name,
    ownerPhone: OWNERS[1].phone,
  },
  {
    propertyType: "pg",
    serviceSlug: "pg-accommodation",
    title: "Premium Boys PG — Madhapur",
    location: "Madhapur, near Hitech City",
    area: "Madhapur",
    lat: 17.4489,
    lng: 78.3912,
    pricePaise: 1099900,
    priceUnit: "month",
    depositPaise: 500000,
    rating: 4.8,
    roomType: "Double sharing AC",
    hasAc: true,
    isFurnished: true,
    sharingType: "double",
    foodIncluded: true,
    genderPreference: "male",
    amenities: ["Meals included", "Laundry", "Wi-Fi", "Gym", "CCTV"],
    rules: ["Male only", "Curfew 11 PM", "No alcohol on premises"],
    ownerName: OWNERS[4].name,
    ownerPhone: OWNERS[4].phone,
  },
  {
    propertyType: "pg",
    serviceSlug: "pg-accommodation",
    title: "Girls PG with Food — Miyapur",
    location: "Miyapur X Roads",
    area: "Miyapur",
    lat: 17.4963,
    lng: 78.3572,
    pricePaise: 949900,
    priceUnit: "month",
    depositPaise: 500000,
    rating: 4.9,
    roomType: "Triple sharing",
    hasAc: true,
    isFurnished: true,
    sharingType: "double",
    foodIncluded: true,
    genderPreference: "female",
    amenities: ["Veg meals", "Wi-Fi", "RO water", "Security"],
    rules: ["Female only", "Parents visit allowed on weekends"],
    ownerName: OWNERS[2].name,
    ownerPhone: OWNERS[2].phone,
  },
  {
    propertyType: "hostels",
    serviceSlug: "hostels",
    title: "Student Hostel — OU Campus Area",
    location: "Near Osmania University",
    area: "Tarnaka",
    lat: 17.4156,
    lng: 78.5289,
    pricePaise: 549900,
    priceUnit: "month",
    depositPaise: 300000,
    rating: 4.5,
    roomType: "Dormitory 4-bed",
    hasAc: false,
    isFurnished: true,
    sharingType: "double",
    foodIncluded: true,
    genderPreference: "any",
    amenities: ["Study room", "Meals", "Wi-Fi", "24/7 security"],
    rules: ["Student ID required", "Quiet hours 10 PM–6 AM"],
    ownerName: OWNERS[2].name,
    ownerPhone: OWNERS[2].phone,
  },
  {
    propertyType: "hostels",
    serviceSlug: "hostels",
    title: "Girls Hostel — Bachupally",
    location: "Bachupally, near colleges",
    area: "Bachupally",
    lat: 17.5421,
    lng: 78.3876,
    pricePaise: 599900,
    priceUnit: "month",
    depositPaise: 350000,
    rating: 4.6,
    roomType: "Twin sharing",
    hasAc: true,
    isFurnished: true,
    sharingType: "double",
    foodIncluded: true,
    genderPreference: "female",
    amenities: ["AC", "Meals", "Laundry", "Wi-Fi"],
    rules: ["Female students only", "Gate closes 9 PM"],
    ownerName: OWNERS[1].name,
    ownerPhone: OWNERS[1].phone,
  },
  {
    propertyType: "apartments",
    serviceSlug: "apartments",
    title: "2 BHK Fully Furnished — Kukatpally",
    location: "KPHB Colony, Kukatpally",
    area: "Kukatpally",
    lat: 17.4948,
    lng: 78.3996,
    pricePaise: 2499900,
    priceUnit: "month",
    depositPaise: 5000000,
    rating: 4.8,
    roomType: "2 BHK apartment",
    hasAc: true,
    isFurnished: true,
    sharingType: "single",
    foodIncluded: false,
    genderPreference: "any",
    amenities: ["AC all rooms", "Modular kitchen", "Parking", "Lift", "Power backup"],
    rules: ["Family preferred", "1 month notice to vacate"],
    ownerName: OWNERS[3].name,
    ownerPhone: OWNERS[3].phone,
  },
  {
    propertyType: "apartments",
    serviceSlug: "apartments",
    title: "1 BHK Semi-Furnished — Manikonda",
    location: "Manikonda, near Lanco Hills",
    area: "Manikonda",
    lat: 17.4012,
    lng: 78.3921,
    pricePaise: 1799900,
    priceUnit: "month",
    depositPaise: 3500000,
    rating: 4.6,
    roomType: "1 BHK apartment",
    hasAc: true,
    isFurnished: false,
    sharingType: "single",
    foodIncluded: false,
    genderPreference: "any",
    amenities: ["Parking", "Lift", "Security"],
    rules: ["11-month agreement", "Maintenance extra"],
    ownerName: OWNERS[0].name,
    ownerPhone: OWNERS[0].phone,
  },
  {
    propertyType: "short-stay",
    serviceSlug: "short-stay",
    title: "Service Apartment — Banjara Hills",
    location: "Road No. 12, Banjara Hills",
    area: "Banjara Hills",
    lat: 17.4234,
    lng: 78.4489,
    pricePaise: 349900,
    priceUnit: "night",
    depositPaise: 200000,
    rating: 4.9,
    roomType: "Studio suite",
    hasAc: true,
    isFurnished: true,
    sharingType: "single",
    foodIncluded: false,
    genderPreference: "any",
    amenities: ["Daily housekeeping", "Wi-Fi", "Kitchenette", "TV"],
    rules: ["Check-in 2 PM", "Check-out 11 AM", "ID mandatory"],
    ownerName: OWNERS[3].name,
    ownerPhone: OWNERS[3].phone,
  },
  {
    propertyType: "short-stay",
    serviceSlug: "short-stay",
    title: "Budget Short Stay — Secunderabad",
    location: "Near Secunderabad Railway Station",
    area: "Secunderabad",
    lat: 17.4399,
    lng: 78.4983,
    pricePaise: 199900,
    priceUnit: "night",
    depositPaise: 100000,
    rating: 4.3,
    roomType: "Standard room",
    hasAc: true,
    isFurnished: true,
    sharingType: "single",
    foodIncluded: false,
    genderPreference: "any",
    amenities: ["Wi-Fi", "Room service", "AC"],
    rules: ["24-hour front desk", "No unregistered guests"],
    ownerName: OWNERS[1].name,
    ownerPhone: OWNERS[1].phone,
  },
  {
    propertyType: "worker-accommodation",
    serviceSlug: "worker-accommodation",
    title: "Labour Camp — Shamshabad",
    location: "Industrial area, Shamshabad",
    area: "Shamshabad",
    lat: 17.2403,
    lng: 78.4294,
    pricePaise: 399900,
    priceUnit: "month",
    depositPaise: 200000,
    rating: 4.4,
    roomType: "Shared dormitory",
    hasAc: false,
    isFurnished: false,
    sharingType: "double",
    foodIncluded: true,
    genderPreference: "male",
    amenities: ["Meals", "Drinking water", "Common washrooms", "Security"],
    rules: ["Company letter preferred", "Bulk booking available"],
    ownerName: OWNERS[4].name,
    ownerPhone: OWNERS[4].phone,
  },
  {
    propertyType: "worker-accommodation",
    serviceSlug: "worker-accommodation",
    title: "Site Worker Housing — Patancheru",
    location: "Patancheru industrial belt",
    area: "Patancheru",
    lat: 17.5289,
    lng: 78.2641,
    pricePaise: 349900,
    priceUnit: "month",
    depositPaise: 150000,
    rating: 4.2,
    roomType: "8-bed dorm",
    hasAc: false,
    isFurnished: false,
    sharingType: "double",
    foodIncluded: true,
    genderPreference: "any",
    amenities: ["Meals twice daily", "Bus to site", "First aid"],
    rules: ["Contractor reference required"],
    ownerName: OWNERS[0].name,
    ownerPhone: OWNERS[0].phone,
  },
];

export function propertyImages(title: string) {
  return [IMG(title), IMG(`${title} 2`), IMG(`${title} 3`)];
}

export { OWNERS };
